package com.neusoft.logistics.bean;
// default package

import java.util.Date;


/**
 * AllocationOrder generated by MyEclipse Persistence Tools
 */

public class AllocationOrder  implements java.io.Serializable {


    // Fields    

     private int allocationorderid;
     private User LUser;
     private Order LOrder;
     private Date allocationdate;
     private String allocationstate;


    // Constructors

    /** default constructor */
    public AllocationOrder() {
    }

    
    /** full constructor */
    public AllocationOrder(User LUser, Order LOrder, Date allocationdate, String allocationstate) {
        this.LUser = LUser;
        this.LOrder = LOrder;
        this.allocationdate = allocationdate;
        this.allocationstate = allocationstate;
    }

   
    // Property accessors

    public int getAllocationorderid() {
        return this.allocationorderid;
    }
    
    public void setAllocationorderid(int allocationorderid) {
        this.allocationorderid = allocationorderid;
    }

    public User getLUser() {
        return this.LUser;
    }
    
    public void setLUser(User LUser) {
        this.LUser = LUser;
    }

    public Order getLOrder() {
        return this.LOrder;
    }
    
    public void setLOrder(Order LOrder) {
        this.LOrder = LOrder;
    }

    public Date getAllocationdate() {
        return this.allocationdate;
    }
    
    public void setAllocationdate(Date allocationdate) {
        this.allocationdate = allocationdate;
    }

    public String getAllocationstate() {
        return this.allocationstate;
    }
    
    public void setAllocationstate(String allocationstate) {
        this.allocationstate = allocationstate;
    }
   








}