package com.neusoft.logistics.bean;
// default package

import java.util.Date;


/**
 * CancelOrder generated by MyEclipse Persistence Tools
 */

public class CancelOrder  implements java.io.Serializable {


    // Fields    

     private int cancelorderid;
     private Order LOrder;
     private String cancelreason;
     private Date canceldate;


    // Constructors

    /** default constructor */
    public CancelOrder() {
    }

    
    /** full constructor */
    public CancelOrder(Order LOrder, String cancelreason, Date canceldate) {
        this.LOrder = LOrder;
        this.cancelreason = cancelreason;
        this.canceldate = canceldate;
    }

   
    // Property accessors

    public int getCancelorderid() {
        return this.cancelorderid;
    }
    
    public void setCancelorderid(int cancelorderid) {
        this.cancelorderid = cancelorderid;
    }

    public Order getLOrder() {
        return this.LOrder;
    }
    
    public void setLOrder(Order LOrder) {
        this.LOrder = LOrder;
    }

    public String getCancelreason() {
        return this.cancelreason;
    }
    
    public void setCancelreason(String cancelreason) {
        this.cancelreason = cancelreason;
    }

    public Date getCanceldate() {
        return this.canceldate;
    }
    
    public void setCanceldate(Date canceldate) {
        this.canceldate = canceldate;
    }
   








}