package com.neusoft.logistics.bean;
// default package

import java.util.Date;


/**
 * ChangeProductOrder generated by MyEclipse Persistence Tools
 */

public class ChangeProductOrder  implements java.io.Serializable {


    // Fields    

     private int changeproductorderid;
     private Product LProduct;
     private Order LOrder;
     private int changequantity;
     private String changereason;
     private Date changedate;


    // Constructors

    /** default constructor */
    public ChangeProductOrder() {
    }

    
    /** full constructor */
    public ChangeProductOrder(Product LProduct, Order LOrder, int changequantity, String changereason, Date changedate) {
        this.LProduct = LProduct;
        this.LOrder = LOrder;
        this.changequantity = changequantity;
        this.changereason = changereason;
        this.changedate = changedate;
    }

   
    // Property accessors

    public int getChangeproductorderid() {
        return this.changeproductorderid;
    }
    
    public void setChangeproductorderid(int changeproductorderid) {
        this.changeproductorderid = changeproductorderid;
    }

    public Product getLProduct() {
        return this.LProduct;
    }
    
    public void setLProduct(Product LProduct) {
        this.LProduct = LProduct;
    }

    public Order getLOrder() {
        return this.LOrder;
    }
    
    public void setLOrder(Order LOrder) {
        this.LOrder = LOrder;
    }

    public int getChangequantity() {
        return this.changequantity;
    }
    
    public void setChangequantity(int changequantity) {
        this.changequantity = changequantity;
    }

    public String getChangereason() {
        return this.changereason;
    }
    
    public void setChangereason(String changereason) {
        this.changereason = changereason;
    }

    public Date getChangedate() {
        return this.changedate;
    }
    
    public void setChangedate(Date changedate) {
        this.changedate = changedate;
    }
   








}