package com.neusoft.logistics.bean;
// default package

import java.util.HashSet;
import java.util.Set;


/**
 * Customer generated by MyEclipse Persistence Tools
 */

public class Customer  implements java.io.Serializable {


    // Fields    

     private int customerid;
     private String customername;
     private String idcard;
     private String workplace;
     private String phone;
     private String mobile;
     private String address;
     private String customerzipcode;
     private String email;
     private Set LOrders = new HashSet(0);


    // Constructors

    /** default constructor */
    public Customer() {
    }

    
    /** full constructor */
    public Customer(String customername, String idcard, String workplace, String phone, String mobile, String address, String customerzipcode, String email, Set LOrders) {
        this.customername = customername;
        this.idcard = idcard;
        this.workplace = workplace;
        this.phone = phone;
        this.mobile = mobile;
        this.address = address;
        this.customerzipcode = customerzipcode;
        this.email = email;
        this.LOrders = LOrders;
    }

   
    // Property accessors

    public int getCustomerid() {
        return this.customerid;
    }
    
    public void setCustomerid(int customerid) {
        this.customerid = customerid;
    }

    public String getCustomername() {
        return this.customername;
    }
    
    public void setCustomername(String customername) {
        this.customername = customername;
    }

    public String getIdcard() {
        return this.idcard;
    }
    
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    public String getWorkplace() {
        return this.workplace;
    }
    
    public void setWorkplace(String workplace) {
        this.workplace = workplace;
    }

    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public String getCustomerzipcode() {
        return this.customerzipcode;
    }
    
    public void setCustomerzipcode(String customerzipcode) {
        this.customerzipcode = customerzipcode;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public Set getLOrders() {
        return this.LOrders;
    }
    
    public void setLOrders(Set LOrders) {
        this.LOrders = LOrders;
    }
   








}