package com.neusoft.logistics.bean;

// default package

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * DispatchOrder generated by MyEclipse Persistence Tools
 */

public class DispatchOrder  implements java.io.Serializable {


    // Fields    
     private int dispatchorderid;
     private Warehouse LWarehouse;
     private User LUserBySignedman;
     private User LUserByOperator;
     private OutStorageOrder LOutstorageorder;
     private User LUserByDispatchman;
     private String dipatchorderremark;
     private Date dipatchdate;
     private Set LSubsationinstorageorders = new HashSet(0);
     private Set LDispatchorderitems = new HashSet(0);


    // Constructors

    /** default constructor */
    public DispatchOrder() {
    }

    
    /** full constructor */
    public DispatchOrder(Warehouse LWarehouse, User LUserBySignedman, User LUserByOperator, OutStorageOrder LOutstorageorder, User LUserByDispatchman, String dipatchorderremark, Date dipatchdate, Set LSubsationinstorageorders, Set LDispatchorderitems) {
        this.LWarehouse = LWarehouse;
        this.LUserBySignedman = LUserBySignedman;
        this.LUserByOperator = LUserByOperator;
        this.LOutstorageorder = LOutstorageorder;
        this.LUserByDispatchman = LUserByDispatchman;
        this.dipatchorderremark = dipatchorderremark;
        this.dipatchdate = dipatchdate;
        this.LSubsationinstorageorders = LSubsationinstorageorders;
        this.LDispatchorderitems = LDispatchorderitems;
    }

   
    // Property accessors

    public int getDispatchorderid() {
        return this.dispatchorderid;
    }
    
    public void setDispatchorderid(int dispatchorderid) {
        this.dispatchorderid = dispatchorderid;
    }

    public Warehouse getLWarehouse() {
        return this.LWarehouse;
    }
    
    public void setLWarehouse(Warehouse LWarehouse) {
        this.LWarehouse = LWarehouse;
    }

    public User getLUserBySignedman() {
        return this.LUserBySignedman;
    }
    
    public void setLUserBySignedman(User LUserBySignedman) {
        this.LUserBySignedman = LUserBySignedman;
    }

    public User getLUserByOperator() {
        return this.LUserByOperator;
    }
    
    public void setLUserByOperator(User LUserByOperator) {
        this.LUserByOperator = LUserByOperator;
    }

    public OutStorageOrder getLOutstorageorder() {
        return this.LOutstorageorder;
    }
    
    public void setLOutstorageorder(OutStorageOrder LOutstorageorder) {
        this.LOutstorageorder = LOutstorageorder;
    }

    public User getLUserByDispatchman() {
        return this.LUserByDispatchman;
    }
    
    public void setLUserByDispatchman(User LUserByDispatchman) {
        this.LUserByDispatchman = LUserByDispatchman;
    }

    public String getDipatchorderremark() {
        return this.dipatchorderremark;
    }
    
    public void setDipatchorderremark(String dipatchorderremark) {
        this.dipatchorderremark = dipatchorderremark;
    }

    public Date getDipatchdate() {
        return this.dipatchdate;
    }
    
    public void setDipatchdate(Date dipatchdate) {
        this.dipatchdate = dipatchdate;
    }

    public Set getLSubsationinstorageorders() {
        return this.LSubsationinstorageorders;
    }
    
    public void setLSubsationinstorageorders(Set LSubsationinstorageorders) {
        this.LSubsationinstorageorders = LSubsationinstorageorders;
    }

    public Set getLDispatchorderitems() {
        return this.LDispatchorderitems;
    }
    
    public void setLDispatchorderitems(Set LDispatchorderitems) {
        this.LDispatchorderitems = LDispatchorderitems;
    }
   








}