package com.neusoft.logistics.bean;
// default package



/**
 * DispatchOrderItem generated by MyEclipse Persistence Tools
 */

public class DispatchOrderItem  implements java.io.Serializable {


    // Fields    

     private int dispatchorderitemid;
     private DispatchOrder LDispatchorder;
     private Product LProduct;
     private int productquantity;


    // Constructors

    /** default constructor */
    public DispatchOrderItem() {
    }

    
    /** full constructor */
    public DispatchOrderItem(DispatchOrder LDispatchorder, Product LProduct, int productquantity) {
        this.LDispatchorder = LDispatchorder;
        this.LProduct = LProduct;
        this.productquantity = productquantity;
    }

   
    // Property accessors

    public int getDispatchorderitemid() {
        return this.dispatchorderitemid;
    }
    
    public void setDispatchorderitemid(int dispatchorderitemid) {
        this.dispatchorderitemid = dispatchorderitemid;
    }

    public DispatchOrder getLDispatchorder() {
        return this.LDispatchorder;
    }
    
    public void setLDispatchorder(DispatchOrder LDispatchorder) {
        this.LDispatchorder = LDispatchorder;
    }

    public Product getLProduct() {
        return this.LProduct;
    }
    
    public void setLProduct(Product LProduct) {
        this.LProduct = LProduct;
    }

    public int getProductquantity() {
        return this.productquantity;
    }
    
    public void setProductquantity(int productquantity) {
        this.productquantity = productquantity;
    }
   








}