package com.neusoft.logistics.bean;
// default package



/**
 * FeedBackOrder generated by MyEclipse Persistence Tools
 */

public class FeedBackOrder  implements java.io.Serializable {


    // Fields    

     private int feedbackorderid;
     private TaskOrder taskorder;
     private String taskstate;
     private int satisfaction;
     private String feedbackremark;


    // Constructors

    /** default constructor */
    public FeedBackOrder() {
    }

    
    /** full constructor */
    public FeedBackOrder(TaskOrder LSignedorder, String taskstate, int satisfaction, String feedbackremark) {
        this.taskorder = LSignedorder;
        this.taskstate = taskstate;
        this.satisfaction = satisfaction;
        this.feedbackremark = feedbackremark;
    }

   
    // Property accessors

    public int getFeedbackorderid() {
        return this.feedbackorderid;
    }
    
    public void setFeedbackorderid(int feedbackorderid) {
        this.feedbackorderid = feedbackorderid;
    }



    public TaskOrder getTaskorder() {
		return taskorder;
	}


	public void setTaskorder(TaskOrder taskorder) {
		this.taskorder = taskorder;
	}


	public String getTaskstate() {
        return this.taskstate;
    }
    
    public void setTaskstate(String taskstate) {
        this.taskstate = taskstate;
    }

    public int getSatisfaction() {
        return this.satisfaction;
    }
    
    public void setSatisfaction(int satisfaction) {
        this.satisfaction = satisfaction;
    }

    public String getFeedbackremark() {
        return this.feedbackremark;
    }
    
    public void setFeedbackremark(String feedbackremark) {
        this.feedbackremark = feedbackremark;
    }
   








}