package com.neusoft.logistics.bean;

import java.util.List;
import java.util.Set;

// default package



/**
 * Function generated by MyEclipse Persistence Tools
 */

public class Function  implements java.io.Serializable {


    // Fields
     private int functionid; 
     private Role LRoleByRole;
     private Function parent;
     private String functionname;
     private String isleaf;
     private String iconcls; 
     private Set<Function> children;
    // Constructors

    /** default constructor */
    public Function() {
    }

    
    /** full constructor */
    public Function(Role LRoleByRole, Function parent, String functionname, String isleaf, String iconcls) {
         
        this.LRoleByRole = LRoleByRole; 
        this.parent=parent;
        this.functionname = functionname;
        this.isleaf = isleaf;
        this.iconcls = iconcls; 
    }

   
    // Property accessors

    public int getFunctionid() {
        return this.functionid;
    }
    
    public void setFunctionid(int functionid) {
        this.functionid = functionid;
    }

    

    public Role getLRoleByRole() {
        return this.LRoleByRole;
    }
    
    public void setLRoleByRole(Role LRoleByRole) {
        this.LRoleByRole = LRoleByRole;
    }

   
    public String getFunctionname() {
        return this.functionname;
    }
    
    public void setFunctionname(String functionname) {
        this.functionname = functionname;
    }

    public String getIsleaf() {
        return this.isleaf;
    }
    
    public void setIsleaf(String isleaf) {
        this.isleaf = isleaf;
    }

    public String getIconcls() {
        return this.iconcls;
    }
    
    public void setIconcls(String iconcls) {
        this.iconcls = iconcls;
    }


	public Function getParent() {
		return parent;
	}


	public void setParent(Function parent) {
		this.parent = parent;
	}


	public Set<Function> getChildren() {
		return children;
	}


	public void setChildren(Set<Function> children) {
		this.children = children;
	}


}