package com.neusoft.logistics.bean;
// default package

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by MyEclipse Persistence Tools
 */

public class Order  implements java.io.Serializable {


    // Fields    

     private int orderid;
     private Substation LSubstationByCheckoutsubstation;
     private Substation LSubstationByDeliversubstation;
     private User LUser;
     private Customer LCustomer;
     private String orderstate;
     private Date requireddate;
     private Date orderdate;
     private String ordertype;
     private String receiveadd;
     private String receiveperson;
     private String receivepersontel;
     private String receivepersonzip;
     private int invoicerequired;
     private String payer;
     private String payeradd;
     private String payertel;
     private String payerzipcode;
     private Set LTaskorders = new HashSet(0);
     private Set LAllocationorders = new HashSet(0);
     private Set LShortageorders = new HashSet(0);
     private Set LCancelorders = new HashSet(0);
     private Set LChangeproductorders = new HashSet(0);
     private Set<OrderItem> LOrderitems = new HashSet<OrderItem>(0);


    // Constructors

    /** default constructor */
    public Order() {
    }

    
    /** full constructor */
    public Order(Substation LSubstationByCheckoutsubstation, Substation LSubstationByDeliversubstation, User LUser, Customer LCustomer, String orderstate, Date requireddate, Date orderdate, String ordertype, String receiveadd, String receiveperson, String receivepersontel, String receivepersonzip, int invoicerequired, String payer, String payeradd, String payertel, String payerzipcode, Set LTaskorders, Set LAllocationorders, Set LShortageorders, Set LCancelorders, Set LChangeproductorders, Set LOrderitems) {
        this.LSubstationByCheckoutsubstation = LSubstationByCheckoutsubstation;
        this.LSubstationByDeliversubstation = LSubstationByDeliversubstation;
        this.LUser = LUser;
        this.LCustomer = LCustomer;
        this.orderstate = orderstate;
        this.requireddate = requireddate;
        this.orderdate = orderdate;
        this.ordertype = ordertype;
        this.receiveadd = receiveadd;
        this.receiveperson = receiveperson;
        this.receivepersontel = receivepersontel;
        this.receivepersonzip = receivepersonzip;
        this.invoicerequired = invoicerequired;
        this.payer = payer;
        this.payeradd = payeradd;
        this.payertel = payertel;
        this.payerzipcode = payerzipcode;
        this.LTaskorders = LTaskorders;
        this.LAllocationorders = LAllocationorders;
        this.LShortageorders = LShortageorders;
        this.LCancelorders = LCancelorders;
        this.LChangeproductorders = LChangeproductorders;
        this.LOrderitems = LOrderitems;
    }

   
    // Property accessors

    public int getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(int orderid) {
        this.orderid = orderid;
    }

    public Substation getLSubstationByCheckoutsubstation() {
        return this.LSubstationByCheckoutsubstation;
    }
    
    public void setLSubstationByCheckoutsubstation(Substation LSubstationByCheckoutsubstation) {
        this.LSubstationByCheckoutsubstation = LSubstationByCheckoutsubstation;
    }

    public Substation getLSubstationByDeliversubstation() {
        return this.LSubstationByDeliversubstation;
    }
    
    public void setLSubstationByDeliversubstation(Substation LSubstationByDeliversubstation) {
        this.LSubstationByDeliversubstation = LSubstationByDeliversubstation;
    }

    public User getLUser() {
        return this.LUser;
    }
    
    public void setLUser(User LUser) {
        this.LUser = LUser;
    }

    public Customer getLCustomer() {
        return this.LCustomer;
    }
    
    public void setLCustomer(Customer LCustomer) {
        this.LCustomer = LCustomer;
    }

    public String getOrderstate() {
        return this.orderstate;
    }
    
    public void setOrderstate(String orderstate) {
        this.orderstate = orderstate;
    }

    public Date getRequireddate() {
        return this.requireddate;
    }
    
    public void setRequireddate(Date requireddate) {
        this.requireddate = requireddate;
    }

    public Date getOrderdate() {
        return this.orderdate;
    }
    
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }

    public String getOrdertype() {
        return this.ordertype;
    }
    
    public void setOrdertype(String ordertype) {
        this.ordertype = ordertype;
    }

    public String getReceiveadd() {
        return this.receiveadd;
    }
    
    public void setReceiveadd(String receiveadd) {
        this.receiveadd = receiveadd;
    }

    public String getReceiveperson() {
        return this.receiveperson;
    }
    
    public void setReceiveperson(String receiveperson) {
        this.receiveperson = receiveperson;
    }

    public String getReceivepersontel() {
        return this.receivepersontel;
    }
    
    public void setReceivepersontel(String receivepersontel) {
        this.receivepersontel = receivepersontel;
    }

    public String getReceivepersonzip() {
        return this.receivepersonzip;
    }
    
    public void setReceivepersonzip(String receivepersonzip) {
        this.receivepersonzip = receivepersonzip;
    }

    public int getInvoicerequired() {
        return this.invoicerequired;
    }
    
    public void setInvoicerequired(int invoicerequired) {
        this.invoicerequired = invoicerequired;
    }

    public String getPayer() {
        return this.payer;
    }
    
    public void setPayer(String payer) {
        this.payer = payer;
    }

    public String getPayeradd() {
        return this.payeradd;
    }
    
    public void setPayeradd(String payeradd) {
        this.payeradd = payeradd;
    }

    public String getPayertel() {
        return this.payertel;
    }
    
    public void setPayertel(String payertel) {
        this.payertel = payertel;
    }

    public String getPayerzipcode() {
        return this.payerzipcode;
    }
    
    public void setPayerzipcode(String payerzipcode) {
        this.payerzipcode = payerzipcode;
    }

    public Set getLTaskorders() {
        return this.LTaskorders;
    }
    
    public void setLTaskorders(Set LTaskorders) {
        this.LTaskorders = LTaskorders;
    }

    public Set getLAllocationorders() {
        return this.LAllocationorders;
    }
    
    public void setLAllocationorders(Set LAllocationorders) {
        this.LAllocationorders = LAllocationorders;
    }

    public Set getLShortageorders() {
        return this.LShortageorders;
    }
    
    public void setLShortageorders(Set LShortageorders) {
        this.LShortageorders = LShortageorders;
    }

    public Set getLCancelorders() {
        return this.LCancelorders;
    }
    
    public void setLCancelorders(Set LCancelorders) {
        this.LCancelorders = LCancelorders;
    }

    public Set getLChangeproductorders() {
        return this.LChangeproductorders;
    }
    
    public void setLChangeproductorders(Set LChangeproductorders) {
        this.LChangeproductorders = LChangeproductorders;
    }


	public Set<OrderItem> getLOrderitems() {
		return LOrderitems;
	}


	public void setLOrderitems(Set<OrderItem> orderitems) {
		LOrderitems = orderitems;
	}









}