package com.neusoft.logistics.bean;
// default package



/**
 * OrderItem generated by MyEclipse Persistence Tools
 */

public class OrderItem  implements java.io.Serializable {


    // Fields    

     private int orderitemid;
     private Product LProduct;
     private Order LOrder;
     private String firstcatergory;
     private String secondcategory;
     private String productname;
     private String unit;
     private double originalprice;
     private double discount;
     private String productremark;
     private int orderitemamount;
     private double totalPrice;
    // Constructors

    /** default constructor */
    public OrderItem() {
    }

    
    /** full constructor */
    public OrderItem(Product LProduct, Order LOrder, String firstcatergory, String secondcategory, String productname, String unit, double originalprice, double discount, String productremark, int orderitemamount) {
        this.LProduct = LProduct;
        this.LOrder = LOrder;
        this.firstcatergory = firstcatergory;
        this.secondcategory = secondcategory;
        this.productname = productname;
        this.unit = unit;
        this.originalprice = originalprice;
        this.discount = discount;
        this.productremark = productremark;
        this.orderitemamount = orderitemamount;
    }

   
    // Property accessors

    public int getOrderitemid() {
        return this.orderitemid;
    }
    
    public void setOrderitemid(int orderitemid) {
        this.orderitemid = orderitemid;
    }

    public Product getLProduct() {
        return this.LProduct;
    }
    
    public void setLProduct(Product LProduct) {
        this.LProduct = LProduct;
    }

    public Order getLOrder() {
        return this.LOrder;
    }
    
    public void setLOrder(Order LOrder) {
        this.LOrder = LOrder;
    }

    public String getFirstcatergory() {
        return this.firstcatergory;
    }
    
    public void setFirstcatergory(String firstcatergory) {
        this.firstcatergory = firstcatergory;
    }

    public String getSecondcategory() {
        return this.secondcategory;
    }
    
    public void setSecondcategory(String secondcategory) {
        this.secondcategory = secondcategory;
    }

    public String getProductname() {
        return this.productname;
    }
    
    public void setProductname(String productname) {
        this.productname = productname;
    }

    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }

   

    public double getOriginalprice() {
		return originalprice;
	}


	public void setOriginalprice(double originalprice) {
		this.originalprice = originalprice;
	}


	public double getDiscount() {
		return discount;
	}


	public void setDiscount(double discount) {
		this.discount = discount;
	}


	public String getProductremark() {
        return this.productremark;
    }
    
    public void setProductremark(String productremark) {
        this.productremark = productremark;
    }

    public int getOrderitemamount() {
        return this.orderitemamount;
    }
    
    public void setOrderitemamount(int orderitemamount) {
        this.orderitemamount = orderitemamount;
    }

    
	public void setTotalPrice(double totalPrice) {
		this.totalPrice = totalPrice;
	}


	public double getTotalPrice() {
		return totalPrice;
	}
   public boolean equals(Product p){ 
	   return   p.equals(this.getLProduct());
   }
   public boolean equals(Object o){
	   if(o instanceof OrderItem)return ((OrderItem)o).getOrderitemid()==this.getOrderitemid();
	   return  false;
   }








}