package com.neusoft.logistics.bean;
// default package



/**
 * OutStorageOrderItem generated by MyEclipse Persistence Tools
 */

public class OutStorageOrderItem  implements java.io.Serializable {


    // Fields    

     private int outstorageorderitemid;
     private Product LProduct;
     private OutStorageOrder LOutstorageorder;
     private int productquantity;


    // Constructors

    /** default constructor */
    public OutStorageOrderItem() {
    }

    
    /** full constructor */
    public OutStorageOrderItem(Product LProduct, OutStorageOrder LOutstorageorder, int productquantity) {
        this.LProduct = LProduct;
        this.LOutstorageorder = LOutstorageorder;
        this.productquantity = productquantity;
    }

   
    // Property accessors

    public int getOutstorageorderitemid() {
        return this.outstorageorderitemid;
    }
    
    public void setOutstorageorderitemid(int outstorageorderitemid) {
        this.outstorageorderitemid = outstorageorderitemid;
    }

    public Product getLProduct() {
        return this.LProduct;
    }
    
    public void setLProduct(Product LProduct) {
        this.LProduct = LProduct;
    }

    public OutStorageOrder getLOutstorageorder() {
        return this.LOutstorageorder;
    }
    
    public void setLOutstorageorder(OutStorageOrder LOutstorageorder) {
        this.LOutstorageorder = LOutstorageorder;
    }

    public int getProductquantity() {
        return this.productquantity;
    }
    
    public void setProductquantity(int productquantity) {
        this.productquantity = productquantity;
    }
   








}