package com.neusoft.logistics.bean;
// default package

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * OutStorageOrder generated by MyEclipse Persistence Tools
 */

public class OutStorageOrder  implements java.io.Serializable {


    // Fields    

     private int outstorageorderid;
     private Warehouse LWarehouse;
     private Date outstoragedate;
     private String outstorageremark;
     private Set LDispatchorders = new HashSet(0);
     private Set LOutstorageorderitems = new HashSet(0);


    // Constructors

    /** default constructor */
    public OutStorageOrder() {
    }

    
    /** full constructor */
    public OutStorageOrder(Warehouse LWarehouse, Date outstoragedate, String outstorageremark, Set LDispatchorders, Set LOutstorageorderitems) {
        this.LWarehouse = LWarehouse;
        this.outstoragedate = outstoragedate;
        this.outstorageremark = outstorageremark;
        this.LDispatchorders = LDispatchorders;
        this.LOutstorageorderitems = LOutstorageorderitems;
    }

   
    // Property accessors

    public int getOutstorageorderid() {
        return this.outstorageorderid;
    }
    
    public void setOutstorageorderid(int outstorageorderid) {
        this.outstorageorderid = outstorageorderid;
    }

    public Warehouse getLWarehouse() {
        return this.LWarehouse;
    }
    
    public void setLWarehouse(Warehouse LWarehouse) {
        this.LWarehouse = LWarehouse;
    }

    public Date getOutstoragedate() {
        return this.outstoragedate;
    }
    
    public void setOutstoragedate(Date outstoragedate) {
        this.outstoragedate = outstoragedate;
    }

    public String getOutstorageremark() {
        return this.outstorageremark;
    }
    
    public void setOutstorageremark(String outstorageremark) {
        this.outstorageremark = outstorageremark;
    }

    public Set getLDispatchorders() {
        return this.LDispatchorders;
    }
    
    public void setLDispatchorders(Set LDispatchorders) {
        this.LDispatchorders = LDispatchorders;
    }

    public Set getLOutstorageorderitems() {
        return this.LOutstorageorderitems;
    }
    
    public void setLOutstorageorderitems(Set LOutstorageorderitems) {
        this.LOutstorageorderitems = LOutstorageorderitems;
    }
   








}