package com.neusoft.logistics.bean;
// default package

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Product generated by MyEclipse Persistence Tools
 */

public class Product  implements java.io.Serializable {


    // Fields    

     private int productid;
     private Supplier LSupplier;
     private Category LCategory;
     private String productname;
     private String unit;
     private double originalprice;
     private double discount;
     private double costprice;
     private String producttype;
     private String manufacturer;
     private Date guaranteeperiod;
     private int returnable;
     private int changeable;
     
     private String productremark;
     private Set LReturnproductorders = new HashSet(0);
     private Set LOutstorageorderitems = new HashSet(0);
     private Set LOrderitems = new HashSet(0);
     private Set LStorageinfos = new HashSet(0);
     private Set LShortageorders = new HashSet(0);
     private Set LDispatchorderitems = new HashSet(0);
     private Set LPurchaseproductorders = new HashSet(0);
     private Set LPurchasepinstorageorderitems = new HashSet(0);
     private Set LSubsationinstorageorderitems = new HashSet(0);
     private Set LChangeproductorders = new HashSet(0);


    // Constructors

    /** default constructor */
    public Product() {
    }

    
    /** full constructor */
    public Product(Supplier LSupplier, Category LCategory, String productname, String unit, int originalprice, int discount, int costprice, String producttype, String manufacturer, Date guaranteeperiod, int returnable, int changeable, String productremark, Set LReturnproductorders, Set LOutstorageorderitems, Set LOrderitems, Set LStorageinfos, Set LShortageorders, Set LDispatchorderitems, Set LPurchaseproductorders, Set LPurchasepinstorageorderitems, Set LSubsationinstorageorderitems, Set LChangeproductorders) {
        this.LSupplier = LSupplier;
        this.LCategory = LCategory;
        this.productname = productname;
        this.unit = unit;
        this.originalprice = originalprice;
        this.discount = discount;
        this.costprice = costprice;
        this.producttype = producttype;
        this.manufacturer = manufacturer;
        this.guaranteeperiod = guaranteeperiod;
        this.returnable = returnable;
        this.changeable = changeable;
        this.productremark = productremark;
        this.LReturnproductorders = LReturnproductorders;
        this.LOutstorageorderitems = LOutstorageorderitems;
        this.LOrderitems = LOrderitems;
        this.LStorageinfos = LStorageinfos;
        this.LShortageorders = LShortageorders;
        this.LDispatchorderitems = LDispatchorderitems;
        this.LPurchaseproductorders = LPurchaseproductorders;
        this.LPurchasepinstorageorderitems = LPurchasepinstorageorderitems;
        this.LSubsationinstorageorderitems = LSubsationinstorageorderitems;
        this.LChangeproductorders = LChangeproductorders;
    }

   
    // Property accessors

    public int getProductid() {
        return this.productid;
    }
    
    public void setProductid(int productid) {
        this.productid = productid;
    }

    public Supplier getLSupplier() {
        return this.LSupplier;
    }
    
    public void setLSupplier(Supplier LSupplier) {
        this.LSupplier = LSupplier;
    }

    public Category getLCategory() {
        return this.LCategory;
    }
    
    public void setLCategory(Category LCategory) {
        this.LCategory = LCategory;
    }

    public String getProductname() {
        return this.productname;
    }
    
    public void setProductname(String productname) {
        this.productname = productname;
    }

    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }

    
    public double getOriginalprice() {
		return originalprice;
	}


	public void setOriginalprice(double originalprice) {
		this.originalprice = originalprice;
	}


	public double getDiscount() {
		return discount;
	}


	public void setDiscount(double discount) {
		this.discount = discount;
	}


	public double getCostprice() {
		return costprice;
	}


	public void setCostprice(double costprice) {
		this.costprice = costprice;
	}


	public String getProducttype() {
        return this.producttype;
    }
    
    public void setProducttype(String producttype) {
        this.producttype = producttype;
    }

    public String getManufacturer() {
        return this.manufacturer;
    }
    
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    public Date getGuaranteeperiod() {
        return this.guaranteeperiod;
    }
    
    public void setGuaranteeperiod(Date guaranteeperiod) {
        this.guaranteeperiod = guaranteeperiod;
    }

    public int getReturnable() {
        return this.returnable;
    }
    
    public void setReturnable(int returnable) {
        this.returnable = returnable;
    }

    public int getChangeable() {
        return this.changeable;
    }
    
    public void setChangeable(int changeable) {
        this.changeable = changeable;
    }

    public String getProductremark() {
        return this.productremark;
    }
    
    public void setProductremark(String productremark) {
        this.productremark = productremark;
    }

    public Set getLReturnproductorders() {
        return this.LReturnproductorders;
    }
    
    public void setLReturnproductorders(Set LReturnproductorders) {
        this.LReturnproductorders = LReturnproductorders;
    }

    public Set getLOutstorageorderitems() {
        return this.LOutstorageorderitems;
    }
    
    public void setLOutstorageorderitems(Set LOutstorageorderitems) {
        this.LOutstorageorderitems = LOutstorageorderitems;
    }

    public Set getLOrderitems() {
        return this.LOrderitems;
    }
    
    public void setLOrderitems(Set LOrderitems) {
        this.LOrderitems = LOrderitems;
    }

    public Set getLStorageinfos() {
        return this.LStorageinfos;
    }
    
    public void setLStorageinfos(Set LStorageinfos) {
        this.LStorageinfos = LStorageinfos;
    }

    public Set getLShortageorders() {
        return this.LShortageorders;
    }
    
    public void setLShortageorders(Set LShortageorders) {
        this.LShortageorders = LShortageorders;
    }

    public Set getLDispatchorderitems() {
        return this.LDispatchorderitems;
    }
    
    public void setLDispatchorderitems(Set LDispatchorderitems) {
        this.LDispatchorderitems = LDispatchorderitems;
    }

    public Set getLPurchaseproductorders() {
        return this.LPurchaseproductorders;
    }
    
    public void setLPurchaseproductorders(Set LPurchaseproductorders) {
        this.LPurchaseproductorders = LPurchaseproductorders;
    }

    public Set getLPurchasepinstorageorderitems() {
        return this.LPurchasepinstorageorderitems;
    }
    
    public void setLPurchasepinstorageorderitems(Set LPurchasepinstorageorderitems) {
        this.LPurchasepinstorageorderitems = LPurchasepinstorageorderitems;
    }

    public Set getLSubsationinstorageorderitems() {
        return this.LSubsationinstorageorderitems;
    }
    
    public void setLSubsationinstorageorderitems(Set LSubsationinstorageorderitems) {
        this.LSubsationinstorageorderitems = LSubsationinstorageorderitems;
    }

    public Set getLChangeproductorders() {
        return this.LChangeproductorders;
    }
    
    public void setLChangeproductorders(Set LChangeproductorders) {
        this.LChangeproductorders = LChangeproductorders;
    }
   public boolean equals(Object o){
	   if(o instanceof Product)return ((Product)o).getProductid()==this.getProductid();
	   return false;
   }

}