package com.neusoft.logistics.bean;
// default package



/**
 * PurchaseInStorageOrderItem generated by MyEclipse Persistence Tools
 */

public class PurchaseInStorageOrderItem  implements java.io.Serializable {


    // Fields    

     private int purchaseinstorageorderitemid;
     private Product LProduct;
     private PurchaseProductOrder LPurchaseproductorder;
     private PurchaseInstorageOrder LPurchaseinstorageorder;
     private int realpurchasequantity; 


    // Constructors

    /** default constructor */
    public PurchaseInStorageOrderItem() {
    }

    
    /** full constructor */
    public PurchaseInStorageOrderItem(Product LProduct, PurchaseProductOrder LPurchaseproductorder, PurchaseInstorageOrder LPurchaseinstorageorder, int realpurchasequantity) {
        this.LProduct = LProduct;
        this.LPurchaseproductorder = LPurchaseproductorder;
        this.LPurchaseinstorageorder = LPurchaseinstorageorder;
        this.realpurchasequantity = realpurchasequantity;
    }

   
    // Property accessors

    public int getPurchaseinstorageorderitemid() {
        return this.purchaseinstorageorderitemid;
    }
    
    public void setPurchaseinstorageorderitemid(int purchaseinstorageorderitemid) {
        this.purchaseinstorageorderitemid = purchaseinstorageorderitemid;
    }

    public Product getLProduct() {
        return this.LProduct;
    }
    
    public void setLProduct(Product LProduct) {
        this.LProduct = LProduct;
    }

    public PurchaseProductOrder getLPurchaseproductorder() {
        return this.LPurchaseproductorder;
    }
    
    public void setLPurchaseproductorder(PurchaseProductOrder LPurchaseproductorder) {
        this.LPurchaseproductorder = LPurchaseproductorder;
    }

    public PurchaseInstorageOrder getLPurchaseinstorageorder() {
        return this.LPurchaseinstorageorder;
    }
    
    public void setLPurchaseinstorageorder(PurchaseInstorageOrder LPurchaseinstorageorder) {
        this.LPurchaseinstorageorder = LPurchaseinstorageorder;
    }

    public int getRealpurchasequantity() {
        return this.realpurchasequantity;
    }
    
    public void setRealpurchasequantity(int realpurchasequantity) {
        this.realpurchasequantity = realpurchasequantity;
    }
   








}