package com.neusoft.logistics.bean;
// default package
 
import java.sql.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * PurchaseInstorageOrder generated by MyEclipse Persistence Tools
 */

public class PurchaseInstorageOrder  implements java.io.Serializable {


    // Fields    

     private int purchaseinstorageorderid;
     private String productpurchasestate;
     private Date purchasedate;
     private String puchaseremark;
     private Warehouse LWarehouse;
     private Set LPurchasepinstorageorderitems = new HashSet(0);


    // Constructors

    /** default constructor */
    public PurchaseInstorageOrder() {
    }

    
    /** full constructor */
    public PurchaseInstorageOrder(String productpurchasestate, Date purchasedate, String puchaseremark, Set LPurchasepinstorageorderitems) {
        this.productpurchasestate = productpurchasestate;
        this.purchasedate = purchasedate;
        this.puchaseremark = puchaseremark;
        this.LPurchasepinstorageorderitems = LPurchasepinstorageorderitems;
    }

   
    // Property accessors

    public int getPurchaseinstorageorderid() {
        return this.purchaseinstorageorderid;
    }
    
    public void setPurchaseinstorageorderid(int purchaseinstorageorderid) {
        this.purchaseinstorageorderid = purchaseinstorageorderid;
    }

    public String getProductpurchasestate() {
        return this.productpurchasestate;
    }
    
    public void setProductpurchasestate(String productpurchasestate) {
        this.productpurchasestate = productpurchasestate;
    }

    public Date getPurchasedate() {
        return this.purchasedate;
    }
    
    public void setPurchasedate(Date purchasedate) {
        this.purchasedate = purchasedate;
    }

    public String getPuchaseremark() {
        return this.puchaseremark;
    }
    
    public void setPuchaseremark(String puchaseremark) {
        this.puchaseremark = puchaseremark;
    }

    public Set getLPurchasepinstorageorderitems() {
        return this.LPurchasepinstorageorderitems;
    }
    
    public void setLPurchasepinstorageorderitems(Set LPurchasepinstorageorderitems) {
        this.LPurchasepinstorageorderitems = LPurchasepinstorageorderitems;
    }


	public Warehouse getLWarehouse() {
		return LWarehouse;
	}


	public void setLWarehouse(Warehouse warehouse) {
		LWarehouse = warehouse;
	}
   








}