package com.neusoft.logistics.bean;
// default package

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * PurchaseProductOrder generated by MyEclipse Persistence Tools
 */

public class PurchaseProductOrder  implements java.io.Serializable {


    // Fields    

     private int purchaseproductorderid;
     private Product LProduct;
     private int productquantity; 
     private String purchaseremark;
     private Date purchaseDate;
     private Set LPurchasepinstorageorderitems = new HashSet(0);  

    // Constructors

    /** default constructor */
    public PurchaseProductOrder() {
    }

    
    /** full constructor */
    public PurchaseProductOrder(Product LProduct, int productquantity, String purchaseremark) {
        this.LProduct = LProduct;
        this.productquantity = productquantity;
        this.purchaseremark = purchaseremark;
     }

   
    // Property accessors

 

	public int getPurchaseproductorderid() {
        return this.purchaseproductorderid;
    }
    
    public void setPurchaseproductorderid(int purchaseproductorderid) {
        this.purchaseproductorderid = purchaseproductorderid;
    }

    public Product getLProduct() {
        return this.LProduct;
    }
    
    public void setLProduct(Product LProduct) {
        this.LProduct = LProduct;
    }

    public int getProductquantity() {
        return this.productquantity;
    }
    
    public void setProductquantity(int productquantity) {
        this.productquantity = productquantity;
    }

    public String getPurchaseremark() {
        return this.purchaseremark;
    }
    
    public void setPurchaseremark(String purchaseremark) {
        this.purchaseremark = purchaseremark;
    }


	public Date getPurchaseDate() {
		return purchaseDate;
	}


	public void setPurchaseDate(Date purchaseDate) {
		this.purchaseDate = purchaseDate;
	}


	public Set getLPurchasepinstorageorderitems() {
		return LPurchasepinstorageorderitems;
	}


	public void setLPurchasepinstorageorderitems(Set purchasepinstorageorderitems) {
		LPurchasepinstorageorderitems = purchasepinstorageorderitems;
	}

 
}