package com.neusoft.logistics.bean;
// default package

import java.util.HashSet;
import java.util.Set;


/**
 * Role generated by MyEclipse Persistence Tools
 */

public class Role  implements java.io.Serializable {


    // Fields    

     private int roleid;
     private String rolename;
     private Set LFunctions = new HashSet(0);
     private Set LUsers = new HashSet(0);


    // Constructors

    /** default constructor */
    public Role() {
    }

    
    /** full constructor */
    public Role(String rolename, Set LFunctions, Set LUsers) {
        this.rolename = rolename;
        this.LFunctions = LFunctions;
        this.LUsers = LUsers;
    }

   
    // Property accessors

    public int getRoleid() {
        return this.roleid;
    }
    
    public void setRoleid(int roleid) {
        this.roleid = roleid;
    }

    public String getRolename() {
        return this.rolename;
    }
    
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }

    public Set getLFunctions() {
        return this.LFunctions;
    }
    
    public void setLFunctions(Set LFunctions) {
        this.LFunctions = LFunctions;
    }

    public Set getLUsers() {
        return this.LUsers;
    }
    
    public void setLUsers(Set LUsers) {
        this.LUsers = LUsers;
    }
   








}