package com.neusoft.logistics.bean;
// default package



/**
 * ShortageOrder generated by MyEclipse Persistence Tools
 */

public class ShortageOrder  implements java.io.Serializable {


    // Fields    

     private int shortageorderid;
     private Product LProduct;
     private Order LOrder;
     private int shortagequantity;
     private String shortagestate;


    // Constructors

    /** default constructor */
    public ShortageOrder() {
    }

    
    /** full constructor */
    public ShortageOrder(Product LProduct, Order LOrder, int shortagequantity, String shortagestate) {
        this.LProduct = LProduct;
        this.LOrder = LOrder;
        this.shortagequantity = shortagequantity;
        this.shortagestate = shortagestate;
    }

   
    // Property accessors

    public int getShortageorderid() {
        return this.shortageorderid;
    }
    
    public void setShortageorderid(int shortageorderid) {
        this.shortageorderid = shortageorderid;
    }

    public Product getLProduct() {
        return this.LProduct;
    }
    
    public void setLProduct(Product LProduct) {
        this.LProduct = LProduct;
    }

    public Order getLOrder() {
        return this.LOrder;
    }
    
    public void setLOrder(Order LOrder) {
        this.LOrder = LOrder;
    }

    public int getShortagequantity() {
        return this.shortagequantity;
    }
    
    public void setShortagequantity(int shortagequantity) {
        this.shortagequantity = shortagequantity;
    }

    public String getShortagestate() {
        return this.shortagestate;
    }
    
    public void setShortagestate(String shortagestate) {
        this.shortagestate = shortagestate;
    }
   








}