package com.neusoft.logistics.bean;
// default package

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * SignerOrder generated by MyEclipse Persistence Tools
 */

public class SignerOrder  implements java.io.Serializable {


    // Fields    

     private int signedorderid;
     private User LUser;
     private TaskOrder LTaskorder;
     private Substation LSubstation;
     private String customersignature;
     private String customerfeedback;
     private Date signeddate;
     private String signedorderremark;
     private String deliverreqiurement; 


    // Constructors

    /** default constructor */
    public SignerOrder() {
    }

    
    /** full constructor */
    public SignerOrder(User LUser, TaskOrder LTaskorder, Substation LSubstation, String customersignature, String customerfeedback, Date signeddate, String signedorderremark, String deliverreqiurement) {
        this.LUser = LUser;
        this.LTaskorder = LTaskorder;
        this.LSubstation = LSubstation;
        this.customersignature = customersignature;
        this.customerfeedback = customerfeedback;
        this.signeddate = signeddate;
        this.signedorderremark = signedorderremark;
        this.deliverreqiurement = deliverreqiurement; 
    }

   
    // Property accessors

    public int getSignedorderid() {
        return this.signedorderid;
    }
    
    public void setSignedorderid(int signedorderid) {
        this.signedorderid = signedorderid;
    }

    public User getLUser() {
        return this.LUser;
    }
    
    public void setLUser(User LUser) {
        this.LUser = LUser;
    }

    public TaskOrder getLTaskorder() {
        return this.LTaskorder;
    }
    
    public void setLTaskorder(TaskOrder LTaskorder) {
        this.LTaskorder = LTaskorder;
    }

    public Substation getLSubstation() {
        return this.LSubstation;
    }
    
    public void setLSubstation(Substation LSubstation) {
        this.LSubstation = LSubstation;
    }

    public String getCustomersignature() {
        return this.customersignature;
    }
    
    public void setCustomersignature(String customersignature) {
        this.customersignature = customersignature;
    }

    public String getCustomerfeedback() {
        return this.customerfeedback;
    }
    
    public void setCustomerfeedback(String customerfeedback) {
        this.customerfeedback = customerfeedback;
    }

    public Date getSigneddate() {
        return this.signeddate;
    }
    
    public void setSigneddate(Date signeddate) {
        this.signeddate = signeddate;
    }

    public String getSignedorderremark() {
        return this.signedorderremark;
    }
    
    public void setSignedorderremark(String signedorderremark) {
        this.signedorderremark = signedorderremark;
    }

    public String getDeliverreqiurement() {
        return this.deliverreqiurement;
    }
    
    public void setDeliverreqiurement(String deliverreqiurement) {
        this.deliverreqiurement = deliverreqiurement;
    }
 
   








}