package com.neusoft.logistics.bean;
// default package



/**
 * StorageInfo generated by MyEclipse Persistence Tools
 */

public class StorageInfo  implements java.io.Serializable {


    // Fields    

     private int storageinfoid;
     private Product LProduct;
     private Warehouse LWarehouse;
     private int warningquantity;
     private int maxquantity;
     private int remainquantity;


    // Constructors

    /** default constructor */
    public StorageInfo() {
    }

    
    /** full constructor */
    public StorageInfo(Product LProduct, Warehouse LWarehouse, int warningquantity, int maxquantity, int remainquantity) {
        this.LProduct = LProduct;
        this.LWarehouse = LWarehouse;
        this.warningquantity = warningquantity;
        this.maxquantity = maxquantity;
        this.remainquantity = remainquantity;
    }

   
    // Property accessors

    public int getStorageinfoid() {
        return this.storageinfoid;
    }
    
    public void setStorageinfoid(int storageinfoid) {
        this.storageinfoid = storageinfoid;
    }

    public Product getLProduct() {
        return this.LProduct;
    }
    
    public void setLProduct(Product LProduct) {
        this.LProduct = LProduct;
    }

    public Warehouse getLWarehouse() {
        return this.LWarehouse;
    }
    
    public void setLWarehouse(Warehouse LWarehouse) {
        this.LWarehouse = LWarehouse;
    }

    public int getWarningquantity() {
        return this.warningquantity;
    }
    
    public void setWarningquantity(int warningquantity) {
        this.warningquantity = warningquantity;
    }

    public int getMaxquantity() {
        return this.maxquantity;
    }
    
    public void setMaxquantity(int maxquantity) {
        this.maxquantity = maxquantity;
    }

    public int getRemainquantity() {
        return this.remainquantity;
    }
    
    public void setRemainquantity(int remainquantity) {
        this.remainquantity = remainquantity;
    }
   








}