package com.neusoft.logistics.bean;
// default package



/**
 * SubstationInStorageOrderItem generated by MyEclipse Persistence Tools
 */

public class SubstationInStorageOrderItem  implements java.io.Serializable {


    // Fields    

     private int subsationinstorageorderitemid;
     private Product LProduct;
     private SubstationInStorageOrder LSubsationinstorageorder;
     private int productquantity;


    // Constructors

    /** default constructor */
    public SubstationInStorageOrderItem() {
    }

    
    /** full constructor */
    public SubstationInStorageOrderItem(Product LProduct, SubstationInStorageOrder LSubsationinstorageorder, int productquantity) {
        this.LProduct = LProduct;
        this.LSubsationinstorageorder = LSubsationinstorageorder;
        this.productquantity = productquantity;
    }

   
    // Property accessors

    public int getSubsationinstorageorderitemid() {
        return this.subsationinstorageorderitemid;
    }
    
    public void setSubsationinstorageorderitemid(int subsationinstorageorderitemid) {
        this.subsationinstorageorderitemid = subsationinstorageorderitemid;
    }

    public Product getLProduct() {
        return this.LProduct;
    }
    
    public void setLProduct(Product LProduct) {
        this.LProduct = LProduct;
    }

    public SubstationInStorageOrder getLSubsationinstorageorder() {
        return this.LSubsationinstorageorder;
    }
    
    public void setLSubsationinstorageorder(SubstationInStorageOrder LSubsationinstorageorder) {
        this.LSubsationinstorageorder = LSubsationinstorageorder;
    }

    public int getProductquantity() {
        return this.productquantity;
    }
    
    public void setProductquantity(int productquantity) {
        this.productquantity = productquantity;
    }
   








}