package com.neusoft.logistics.bean;
// default package

import java.util.HashSet;
import java.util.Set;


/**
 * Substation generated by MyEclipse Persistence Tools
 */

public class Substation  implements java.io.Serializable {


    // Fields    

     private int substationid;
     private Warehouse LWarehouse;
     private String substationadd;
     private String substationtel;
     private Set LSignedorders = new HashSet(0);
     private Set LOrdersForDeliversubstation = new HashSet(0);
     private Set LOrdersForCheckoutsubstation = new HashSet(0);
     private Set LUsers = new HashSet(0);


    // Constructors

    /** default constructor */
    public Substation() {
    }

    
    /** full constructor */
    public Substation(Warehouse LWarehouse, String substationadd, String substationtel, Set LSignedorders, Set LOrdersForDeliversubstation, Set LOrdersForCheckoutsubstation, Set LUsers) {
        this.LWarehouse = LWarehouse;
        this.substationadd = substationadd;
        this.substationtel = substationtel;
        this.LSignedorders = LSignedorders;
        this.LOrdersForDeliversubstation = LOrdersForDeliversubstation;
        this.LOrdersForCheckoutsubstation = LOrdersForCheckoutsubstation;
        this.LUsers = LUsers;
    }

   
    // Property accessors

    public int getSubstationid() {
        return this.substationid;
    }
    
    public void setSubstationid(int substationid) {
        this.substationid = substationid;
    }

    public Warehouse getLWarehouse() {
        return this.LWarehouse;
    }
    
    public void setLWarehouse(Warehouse LWarehouse) {
        this.LWarehouse = LWarehouse;
    }

    public String getSubstationadd() {
        return this.substationadd;
    }
    
    public void setSubstationadd(String substationadd) {
        this.substationadd = substationadd;
    }

    public String getSubstationtel() {
        return this.substationtel;
    }
    
    public void setSubstationtel(String substationtel) {
        this.substationtel = substationtel;
    }

    public Set getLSignedorders() {
        return this.LSignedorders;
    }
    
    public void setLSignedorders(Set LSignedorders) {
        this.LSignedorders = LSignedorders;
    }

    public Set getLOrdersForDeliversubstation() {
        return this.LOrdersForDeliversubstation;
    }
    
    public void setLOrdersForDeliversubstation(Set LOrdersForDeliversubstation) {
        this.LOrdersForDeliversubstation = LOrdersForDeliversubstation;
    }

    public Set getLOrdersForCheckoutsubstation() {
        return this.LOrdersForCheckoutsubstation;
    }
    
    public void setLOrdersForCheckoutsubstation(Set LOrdersForCheckoutsubstation) {
        this.LOrdersForCheckoutsubstation = LOrdersForCheckoutsubstation;
    }

    public Set getLUsers() {
        return this.LUsers;
    }
    
    public void setLUsers(Set LUsers) {
        this.LUsers = LUsers;
    }
   public boolean equals(Object o){
	   if(o instanceof Substation)return this.getSubstationid()==((Substation)(o)).getSubstationid()?true:false;
	   return false;
   }








}