package com.neusoft.logistics.bean;
// default package

import java.util.HashSet;
import java.util.Set;


/**
 * Supplier generated by MyEclipse Persistence Tools
 */

public class Supplier  implements java.io.Serializable {


    // Fields    

     private int supplierid;
     private String suppliername;
     private String supplieradd;
     private String contactperson;
     private String suppliertel;
     private String bank;
     private String bankaccount;
     private String fax;
     private String supplierzipcode;
     private String legalperson;
     private String supplierremark;
     private Set LProducts = new HashSet(0);


    // Constructors

    /** default constructor */
    public Supplier() {
    }

    
    /** full constructor */
    public Supplier(String suppliername, String supplieradd, String contactperson, String suppliertel, String bank, String bankaccount, String fax, String supplierzipcode, String legalperson, String supplierremark, Set LProducts) {
        this.suppliername = suppliername;
        this.supplieradd = supplieradd;
        this.contactperson = contactperson;
        this.suppliertel = suppliertel;
        this.bank = bank;
        this.bankaccount = bankaccount;
        this.fax = fax;
        this.supplierzipcode = supplierzipcode;
        this.legalperson = legalperson;
        this.supplierremark = supplierremark;
        this.LProducts = LProducts;
    }

   
    // Property accessors

    public int getSupplierid() {
        return this.supplierid;
    }
    
    public void setSupplierid(int supplierid) {
        this.supplierid = supplierid;
    }

    public String getSuppliername() {
        return this.suppliername;
    }
    
    public void setSuppliername(String suppliername) {
        this.suppliername = suppliername;
    }

    public String getSupplieradd() {
        return this.supplieradd;
    }
    
    public void setSupplieradd(String supplieradd) {
        this.supplieradd = supplieradd;
    }

    public String getContactperson() {
        return this.contactperson;
    }
    
    public void setContactperson(String contactperson) {
        this.contactperson = contactperson;
    }

    public String getSuppliertel() {
        return this.suppliertel;
    }
    
    public void setSuppliertel(String suppliertel) {
        this.suppliertel = suppliertel;
    }

    public String getBank() {
        return this.bank;
    }
    
    public void setBank(String bank) {
        this.bank = bank;
    }

    public String getBankaccount() {
        return this.bankaccount;
    }
    
    public void setBankaccount(String bankaccount) {
        this.bankaccount = bankaccount;
    }

    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getSupplierzipcode() {
        return this.supplierzipcode;
    }
    
    public void setSupplierzipcode(String supplierzipcode) {
        this.supplierzipcode = supplierzipcode;
    }

    public String getLegalperson() {
        return this.legalperson;
    }
    
    public void setLegalperson(String legalperson) {
        this.legalperson = legalperson;
    }

    public String getSupplierremark() {
        return this.supplierremark;
    }
    
    public void setSupplierremark(String supplierremark) {
        this.supplierremark = supplierremark;
    }

    public Set getLProducts() {
        return this.LProducts;
    }
    
    public void setLProducts(Set LProducts) {
        this.LProducts = LProducts;
    }
   








}