package com.neusoft.logistics.bean;
// default package

import java.util.Date;


/**
 * TakeProductOrder generated by MyEclipse Persistence Tools
 */

public class TakeProductOrder  implements java.io.Serializable {


    // Fields    

     private int takeproductorderid;
     private String deliverman;
     private TaskOrder LTaskorder;
     private Date takedate;


    // Constructors

    public TakeProductOrder(int takeproductorderid, String deliverman,
			TaskOrder taskorder, Date takedate) {
		super();
		this.takeproductorderid = takeproductorderid;
		this.deliverman = deliverman;
		LTaskorder = taskorder;
		this.takedate = takedate;
	}


	/** default constructor */
    public TakeProductOrder() {
    }

    
    /** full constructor */
    

   
    // Property accessors

    public int getTakeproductorderid() {
        return this.takeproductorderid;
    }
    
    public void setTakeproductorderid(int takeproductorderid) {
        this.takeproductorderid = takeproductorderid;
    }
    

    public String getDeliverman() {
		return deliverman;
	}


	public void setDeliverman(String deliverman) {
		this.deliverman = deliverman;
	}


	public TaskOrder getLTaskorder() {
        return this.LTaskorder;
    }
    
    public void setLTaskorder(TaskOrder LTaskorder) {
        this.LTaskorder = LTaskorder;
    }

    public Date getTakedate() {
        return this.takedate;
    }
    
    public void setTakedate(Date takedate) {
        this.takedate = takedate;
    }
   








}