package com.neusoft.logistics.bean;
// default package

import java.util.HashSet;
import java.util.Set;


/**
 * User generated by MyEclipse Persistence Tools
 */

public class User  implements java.io.Serializable {


    // Fields    

     private int userid;
     private Role LRole;
     private String username;
     private String passwd;
     private Set LWarehouses = new HashSet(0);
     private Set LSignedorders = new HashSet(0);
     private Set LDispatchordersForDispatchman = new HashSet(0);
     private Set LTaskordersForOperator = new HashSet(0);
     private Set LTakeproductorders = new HashSet(0);
     private Set<Substation> LSubstations = new HashSet<Substation>(0);
    // private Substation substation;
     private Set LAllocationorders = new HashSet(0);
     private Set LTaskordersForDeliverman = new HashSet(0);
     private Set LOrders = new HashSet(0);
     private Set LDispatchordersForOperator = new HashSet(0);


    // Constructors

    /** default constructor */
    public User() {
    }

    
    /** full constructor */
    public User(Role LRole, String username, String passwd, Set LWarehouses, Set LSignedorders, Set LDispatchordersForDispatchman, Set LTaskordersForOperator, Set LTakeproductorders, Set LSubstations, Set LAllocationorders, Set LTaskordersForDeliverman, Set LOrders, Set LDispatchordersForOperator) {
        this.LRole = LRole;
        this.username = username;
        this.passwd = passwd;
        this.LWarehouses = LWarehouses;
        this.LSignedorders = LSignedorders;
        this.LDispatchordersForDispatchman = LDispatchordersForDispatchman;
        this.LTaskordersForOperator = LTaskordersForOperator;
        this.LTakeproductorders = LTakeproductorders;
        this.LSubstations = LSubstations;
        this.LAllocationorders = LAllocationorders;
        this.LTaskordersForDeliverman = LTaskordersForDeliverman;
        this.LOrders = LOrders;
        this.LDispatchordersForOperator = LDispatchordersForOperator;
    }

   
    // Property accessors

    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }

    public Role getLRole() {
        return this.LRole;
    }
    
    public void setLRole(Role LRole) {
        this.LRole = LRole;
    }

    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    public String getPasswd() {
        return this.passwd;
    }
    
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    public Set getLWarehouses() {
        return this.LWarehouses;
    }
    
    public void setLWarehouses(Set LWarehouses) {
        this.LWarehouses = LWarehouses;
    }

    public Set getLSignedorders() {
        return this.LSignedorders;
    }
    
    public void setLSignedorders(Set LSignedorders) {
        this.LSignedorders = LSignedorders;
    }

    public Set getLDispatchordersForDispatchman() {
        return this.LDispatchordersForDispatchman;
    }
    
    public void setLDispatchordersForDispatchman(Set LDispatchordersForDispatchman) {
        this.LDispatchordersForDispatchman = LDispatchordersForDispatchman;
    }

    public Set getLTaskordersForOperator() {
        return this.LTaskordersForOperator;
    }
    
    public void setLTaskordersForOperator(Set LTaskordersForOperator) {
        this.LTaskordersForOperator = LTaskordersForOperator;
    }

    public Set getLTakeproductorders() {
        return this.LTakeproductorders;
    }
    
    public void setLTakeproductorders(Set LTakeproductorders) {
        this.LTakeproductorders = LTakeproductorders;
    }

   

    public Set<Substation> getLSubstations() {
		return LSubstations;
	}


	public void setLSubstations(Set<Substation> substations) {
		LSubstations = substations;
	}


	public Set getLAllocationorders() {
        return this.LAllocationorders;
    }
    
    public void setLAllocationorders(Set LAllocationorders) {
        this.LAllocationorders = LAllocationorders;
    }

    public Set getLTaskordersForDeliverman() {
        return this.LTaskordersForDeliverman;
    }
    
    public void setLTaskordersForDeliverman(Set LTaskordersForDeliverman) {
        this.LTaskordersForDeliverman = LTaskordersForDeliverman;
    }

    public Set getLOrders() {
        return this.LOrders;
    }
    
    public void setLOrders(Set LOrders) {
        this.LOrders = LOrders;
    }

    public Set getLDispatchordersForOperator() {
        return this.LDispatchordersForOperator;
    }
    
    public void setLDispatchordersForOperator(Set LDispatchordersForOperator) {
        this.LDispatchordersForOperator = LDispatchordersForOperator;
    }
   








}