package com.neusoft.logistics.bean;
// default package

import java.util.HashSet;
import java.util.Set;


/**
 * Warehouse generated by MyEclipse Persistence Tools
 */

public class Warehouse  implements java.io.Serializable {


    // Fields    

     private int warehouseid;
     private User LUser;
     private String warehousename;
     private String warehouseaddress;
     private String warehousetype;
     private Set LStorageinfos = new HashSet(0);
     private Set LReturnproductordersForCenterwarehouse = new HashSet(0);
     private Set LDispatchorders = new HashSet(0);
     private Set LOutstorageorders = new HashSet(0);
     private Set LReturnproductordersForSubwarehouse = new HashSet(0);
     private Set LSubstations = new HashSet(0);


    // Constructors

    /** default constructor */
    public Warehouse() {
    }

    
    /** full constructor */
    public Warehouse(User LUser, String warehousename, String warehouseaddress, String warehousetype, Set LStorageinfos, Set LReturnproductordersForCenterwarehouse, Set LDispatchorders, Set LOutstorageorders, Set LReturnproductordersForSubwarehouse, Set LSubstations) {
        this.LUser = LUser;
        this.warehousename = warehousename;
        this.warehouseaddress = warehouseaddress;
        this.warehousetype = warehousetype;
        this.LStorageinfos = LStorageinfos;
        this.LReturnproductordersForCenterwarehouse = LReturnproductordersForCenterwarehouse;
        this.LDispatchorders = LDispatchorders;
        this.LOutstorageorders = LOutstorageorders;
        this.LReturnproductordersForSubwarehouse = LReturnproductordersForSubwarehouse;
        this.LSubstations = LSubstations;
    }

   
    // Property accessors

    public int getWarehouseid() {
        return this.warehouseid;
    }
    
    public void setWarehouseid(int warehouseid) {
        this.warehouseid = warehouseid;
    }

    public User getLUser() {
        return this.LUser;
    }
    
    public void setLUser(User LUser) {
        this.LUser = LUser;
    }

    public String getWarehousename() {
        return this.warehousename;
    }
    
    public void setWarehousename(String warehousename) {
        this.warehousename = warehousename;
    }

    public String getWarehouseaddress() {
        return this.warehouseaddress;
    }
    
    public void setWarehouseaddress(String warehouseaddress) {
        this.warehouseaddress = warehouseaddress;
    }

    public String getWarehousetype() {
        return this.warehousetype;
    }
    
    public void setWarehousetype(String warehousetype) {
        this.warehousetype = warehousetype;
    }

    public Set getLStorageinfos() {
        return this.LStorageinfos;
    }
    
    public void setLStorageinfos(Set LStorageinfos) {
        this.LStorageinfos = LStorageinfos;
    }

    public Set getLReturnproductordersForCenterwarehouse() {
        return this.LReturnproductordersForCenterwarehouse;
    }
    
    public void setLReturnproductordersForCenterwarehouse(Set LReturnproductordersForCenterwarehouse) {
        this.LReturnproductordersForCenterwarehouse = LReturnproductordersForCenterwarehouse;
    }

    public Set getLDispatchorders() {
        return this.LDispatchorders;
    }
    
    public void setLDispatchorders(Set LDispatchorders) {
        this.LDispatchorders = LDispatchorders;
    }

    public Set getLOutstorageorders() {
        return this.LOutstorageorders;
    }
    
    public void setLOutstorageorders(Set LOutstorageorders) {
        this.LOutstorageorders = LOutstorageorders;
    }

    public Set getLReturnproductordersForSubwarehouse() {
        return this.LReturnproductordersForSubwarehouse;
    }
    
    public void setLReturnproductordersForSubwarehouse(Set LReturnproductordersForSubwarehouse) {
        this.LReturnproductordersForSubwarehouse = LReturnproductordersForSubwarehouse;
    }

    public Set getLSubstations() {
        return this.LSubstations;
    }
    
    public void setLSubstations(Set LSubstations) {
        this.LSubstations = LSubstations;
    }
   








}